version: "3.8"
services:
  app:
    env_file:
      - .development.env
    container_name: nest_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    env_file:
      - .development.env
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
