version: "3.8"
services:
  app:
    env_file:
      - .development.env
    environment:
      DB_HOST: host.docker.internal
    container_name: nest_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=nest_boilerplate
    ports:
      - "5434:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
